-- Monthly source for the Operations visualization "Cambio de nota".
-- Only the latest upload for a month is retained by the client replacement
-- flow; alert history and the existing exports remain untouched.

create table if not exists public.admin_note_score_imports (
  period_month date primary key,
  source_filename text not null,
  row_count integer not null default 0 check (row_count >= 0),
  imported_at timestamptz not null default now(),
  imported_by uuid references auth.users(id) on delete set null,
  constraint admin_note_score_imports_period_month_check
    check (period_month = date_trunc('month', period_month)::date)
);

create table if not exists public.admin_note_score_records (
  id bigint generated by default as identity primary key,
  period_month date not null,
  audit_external_id text,
  pdv_id text not null,
  source text,
  subkpi text not null,
  wave text,
  kpi text,
  score numeric(8,4) not null,
  constraint admin_note_score_records_period_month_check
    check (period_month = date_trunc('month', period_month)::date),
  constraint admin_note_score_records_score_check
    check (score >= 0 and score <= 1)
);

create unique index if not exists admin_note_score_records_month_pdv_subkpi_idx
  on public.admin_note_score_records (period_month, pdv_id, subkpi);

create index if not exists admin_note_score_records_month_pdv_idx
  on public.admin_note_score_records (period_month, pdv_id);

alter table public.admin_note_score_imports enable row level security;
alter table public.admin_note_score_records enable row level security;

revoke all on table public.admin_note_score_imports from public, anon;
revoke all on table public.admin_note_score_records from public, anon;
grant select, insert, update, delete on table public.admin_note_score_imports to authenticated;
grant select, insert, update, delete on table public.admin_note_score_records to authenticated;
grant usage, select on sequence public.admin_note_score_records_id_seq to authenticated;

create policy "analysis users manage monthly note-score imports"
  on public.admin_note_score_imports
  for all
  to authenticated
  using ((select private.is_analysis_user()))
  with check ((select private.is_analysis_user()));

create policy "analysis users manage monthly note-score records"
  on public.admin_note_score_records
  for all
  to authenticated
  using ((select private.is_analysis_user()))
  with check ((select private.is_analysis_user()));
